export var notifTransition = 'notifTransition';

var defaultEffect = '\n&.' + notifTransition + '-enter.' + notifTransition + '-enter-active {\n\n    transition: opacity 1s ease;\n    transform:   translate(0,0);\n    transform: translate3d(0,0,0);\n    transition-duration: 250ms;\n    transition-property: transform, opacity;\n    transition-timing-function: linear;\n    }\n &.' + notifTransition + '-leave {\n  opacity: 1;\n  transform:   translate(0,0,0);\n  transform: translate3d(0,0,0);\n  transition-property: transform, opacity;\n  transition-duration: 250ms;\n  transition-timing-function: linear;\n}\n';

export var defaultEffectRight = '\n&.' + notifTransition + '-enter {\ntransform:   translate(25rem,0);\ntransform: translate3d(25rem,0,0);\n}\n\n' + defaultEffect + ';\n\n&.' + notifTransition + '-leave.' + notifTransition + '-leave-active {\n   opacity: 0;\n   transform:   translate(25rem,0);\n   transform: translate3d(25rem,0,0);\n}\n';

export var defaultEffectLeft = '\n&.' + notifTransition + '-enter {\n\n  transform:   translate(-25rem,0);\n  transform: translate3d(-25rem,0,0);\n}\n\n' + defaultEffect + ';\n\n&.' + notifTransition + '-leave.' + notifTransition + '-leave-active {\n   opacity: 0;\n   transform:   translate(-25rem,0);\n   transform: translate3d(-25rem,0,0);\n}\n';

export var defaultEffectTopCenter = '\n&.' + notifTransition + '-enter {\n\n  transform:   translate(0,-25rem);\n  transform: translate3d(0,-25rem,0);\n}\n\n' + defaultEffect + ';\n\n&.' + notifTransition + '-leave.' + notifTransition + '-leave-active {\n   opacity: 0;\n   transform:   translate(0, -25rem);\n   transform: translate3d(0, -25rem,0);\n}\n';

export var defaultEffectBottomCenter = '\n&.' + notifTransition + '-enter {\n\n  transform:   translate(0,25rem);\n  transform: translate3d(0,25rem,0);\n}\n\n' + defaultEffect + ';\n\n&.' + notifTransition + '-leave.' + notifTransition + '-leave-active {\n   opacity: 0;\n   transform:   translate(0, 25rem);\n   transform: translate3d(0, 25rem,0);\n}\n';

export var scaleEffect = '\n&.' + notifTransition + '-enter {\n  opacity: 0;\n  transform: translate3d(0,40px,0) scale3d(0.1,0.6,1);\n\n}\n\n&.' + notifTransition + '-enter.' + notifTransition + '-enter-active {\n\n    opacity: 1;\n    transform: translate3d(0,0,0) scale3d(1,1,1);\n    transition-duration: 250ms;\n    transition-property: transform, opacity;\n    transition-timing-function: linear;\n    }\n &.' + notifTransition + '-leave {\n  opacity: 1;\n  transform: translate3d(0,0,0) scale3d(1,1,1);\n  transition-property: transform, opacity;\n  transition-duration: 250ms;\n  transition-timing-function: linear;\n}\n\n&.' + notifTransition + '-leave.' + notifTransition + '-leave-active {\n  opacity: 0;\n  transform: translate3d(0,40px,0) scale3d(0.1,0.6,1);\n}\n';